### ISSUE TITLE
HA 2024.07.01 async_forward_entry_setup issue

### ISSUE THREAD

**Issue by lordwizzard** [firstof9/ha-gasbuddy#55] opened 2024-07-08 19:05 UTC
So with HA 2024.0701

getting the following errror message:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 11:54:15 AM (4 occurrences)
Last logged: 11:54:15 AM

Detected code that calls async_forward_entry_setup for integration gasbuddy with title: Meijer_gas_station and entry_id: 2fd7a928c9c2e68395df5c9a76dd6bff, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration gasbuddy with title: Costco gas_station and entry_id: 1143b1b683c630c3b649a6fc08a3faf8, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration gasbuddy with title: Murphy_USA_Walmart and entry_id: 7018e1323538c06472b488ea3b9e658d, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration gasbuddy with title: Marathon_Admiral_gas_station and entry_id: cba6095fc788e040f529ef03cefabfa9, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by firstof9** [comment] 2024-07-08 21:22
This is a dupe of #51 this was already fixed in #52

**Closed** 2024-07-11 13:48 UTC
Labels: duplicate
